use_frameworks!

platform :ios, '11.0'

target 'saorsa.PXQuisiteExtensions_Example' do
  pod 'saorsa.PXQuisiteExtensions', :path => '../'

  target 'saorsa.PXQuisiteExtensions_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
