language: objective-c

podfile: Example/Podfile
- set -o pipefail && xcodebuild -workspace Example/saorsa.PXQuisiteExtensions.xcworkspace -scheme saorsa.PXQuisiteExtensions-Example -sdk iphonesimulator | xcpretty
- pod lib lint